config/routes.rb
Rsvp2::Application.routes.draw do
  
  get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
post "login" => 'session#login'

get "nieuws" => "infos#nieuws", :as => "nieuws"
get "fotoboek" => "posts#fotoboek", :as => "fotoboek"
get "admin" => "admin#index", :as => "admin"
get "rsvp" => "users#newrsvp", :as => "newrsvp"

root :to => "infos#nieuws"

resources :posts do
  resources :comments
end
resources :users do
  resources :comments
end
resources :sessions
resources :infos
get "informatie" => "infos#index", :as => "informatie"
match "/:urlname" => "users#rsvpshow", :as => "rsvp"
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post, :foreign_key => 'post_id'
  belongs_to :user , :foreign_key => 'user_id'
  attr_accessible :body, :commenter, :user_id, :post_id
end

app/models/info.rb
class Info < ActiveRecord::Base
  attr_accessible :cont, :titel
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user , :foreign_key => 'user_id'
  has_many :comments 
  attr_accessible :title, :image, :remote_image_url
  mount_uploader :image, ImageUploader
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :answer, :naam, :password, :urlname, :reason
  has_many :posts   
  has_many :comments
  
  validates :naam, presence: true,
                    length: { minimum: 5 }
  validates :password, presence: true,
                    length: { minimum: 5 }
                    
                
  def self.authenticate(naam, password)
    user = User.find_by_naam(naam)
    if user && user.password == password
      user
    else
      nil
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user
  helper_method :admin
 
before_filter :require_login
before_filter :require_admin  

private


  
def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
  
end

def admin
  @admin = User.find_by_naam("Scarlett")
end

def require_admin
  if admin == current_user
  
  else
    redirect_to root_path
  end
end

def require_login
    unless current_user
      redirect_to log_in_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  helper_method :user_finder
  skip_before_filter :require_admin, :only=>[:create]
  def create
    @post = Post.find(params[:post_id])
    
    
    @comment = @post.comments.create(params[:comment].permit(:commenter, :body).merge(:user_id => @current_user.id))
    
   
   
    redirect_to post_path(@post)
  end
  
  
   
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  skip_before_filter :require_login, :only=>[:index, :nieuws]
  skip_before_filter :require_admin, :only=>[:index, :nieuws]
  def index
    @infos = Info.all
  end
  
  def nieuws
    @infos = Info.all
  end
  
  def new
  @info = Info.new
  end
 
  def create
  @info = Info.new(params[:info].permit(:titel, :cont))
 
  if @info.save
    redirect_to @info, :notice => "Infomatie stuk toegevoegd "
  else
    render 'new'
  end
  end

  def show
  @info = Info.find(params[:id])
  end
  
  def edit
  @info = Info.find(params[:id])
  end
  
  def update
  @info = Info.find(params[:id])
 
  if @info.update_attributes(params[:info].permit(:titel, :cont))
    redirect_to @info 
  else
    render 'edit'
  end
end
  
  def destroy
  @info = Info.find(params[:id])
  @info.destroy
 
  redirect_to info_path
end
  
  
private
  def user_params
    params.require(:info).permit(:titel, :cont)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  skip_before_filter :require_admin, :only=>[:new,:create, :fotoboek, :show]
  def index
    @posts = Post.all
  end
def new
  @post = Post.new
end
 
def create
  
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
    @post = @current_user.posts.create(params[:post].permit(:title, :image, :remote_image_url))
    redirect_to post_path(@post)
 
end

def edit
  @post = Post.find(params[:id])
end
  def update
  @post = Post.find(params[:id])
 
  if @post.update_attributes(params[:post].permit(:title, :image, :remote_image_url))
    redirect_to @post
  else
    render 'edit'
  end
end
 
  def show
   @post = Post.find(params[:id])
  end
  def fotoboek
    @posts = Post.all
  end
  def destroy
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    @post = Post.find(params[:id])
    
    @post.destroy
    redirect_to posts_path
  end
private
  def post_params
    params.require(:post).permit(:title)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  skip_before_filter :require_login 
  skip_before_filter :require_admin
  def new
end

def create
  user = User.authenticate(params[:naam], params[:password])
  if user
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Logged in!"
  else
    flash.now.alert = "Invalid email or password"
    render "new"
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Logged out!"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, :only=>[:rsvpshow, :update, :new, :create, :newrsvp, :show]
  skip_before_filter :require_admin, :only=>[:rsvpshow, :update, :new, :create, :show, :edit, :newrsvp]
  def index
    @users = User.all
  end
  
  def new
  @user = User.new
  end
  
  def newrsvp
    @user = User.new
  end
 
  def create
  @user = User.new(params[:user].permit(:naam, :password, :answer, :urlname, :reason))
 
  if @user.save
    redirect_to @user, :notice => "User added"
  else
    render 'new'
  end
  end

  def show
 @user = User.find(params[:id])
  end
  
  def rsvpshow
    @user = User.find_by_urlname params[:urlname]

  end
  
  def edit
  @user = User.find(params[:id])
  end
  
  def update
  @user = User.find(params[:id])
 
  if @user.update_attributes(params[:user].permit(:naam, :answer, :urlname, :password, :reason))
    if @user.id == admin.id
    redirect_to @user
    else 
    redirect_to rsvp_path(@user.urlname), :notice => "Dank je wel voor het reageren. Groetjes, Scarlett & Koen"
    end
  else
    render 'edit'
  end
end
  
  def destroy
  @user = User.find(params[:id])
  @user.destroy
 
  redirect_to users_path
end
  
  
private
  def user_params
    params.require(:user).permit(:naam, :answer, :password, :urlname, :reason)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_menu.html.erb
<%= link_to "Gebruikers", users_path %>
<%= link_to "Gastenboek", posts_path %>
<%= link_to "Informatie", infos_path %>

app/views/admin/index.html.erb
<div class="admin-page">
    <h3>Jouw persoonlijke admin pagina.</h3>
  <div class="admin-menu">
    <%= render 'admin/menu' %>
    </div>
</div>

app/views/infos/_form.html.erb
<%= form_for @info, :html => {:multipart => true} do |f|%>
  <% if @info.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@info.errors.count, "error") %> prohibited
      this info from being saved:</h2>
    <ul>
    <% @info.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
    <div class="admin-form">
       <p>
        <%= f.label :titel %>
        <%= f.text_field :titel %>
      </p>

      <p>
        <%= f.label :inhoud %>
        <%= f.text_field :cont %>
      </p>

      <p>
        <%= f.submit %>
      </p>
    </div>
<% end %>

app/views/infos/edit.html.erb
<div class="admin-page">
<h3>Bericht aanpassen</h3>
  <div class="admin-menu">
    <%= render 'admin/menu' %>
  </div>
<%= render 'form' %> 
<%= link_to 'Back',  infos_path %>
    </div>

app/views/infos/index.html.erb
<div class="admin-page">
  <h3>Berichten op pagina "De Trouwdag"</h3>
  <div class="admin-menu">
    <%= render 'admin/menu' %>
  </div>
  <div class="admin-sub-menu">
    <%= link_to 'Voeg nieuw bericht toe', new_info_path %>
  </div>
  <div class="admin-table">
    <table>
      <tr>
        <th>Titel bericht</th>
        <th>Tekst bericht</th>
      </tr>

      <% @infos.each do |info| %>
        <tr>
          <td><%= info.titel %></td>
          <td><%= info.cont %></td>
           <td><%= link_to 'Show', info %></td>
        <td><%= link_to 'Edit', edit_info_path(info) %></td>
        <td><%= button_to 'Destroy', info_path(info), method: :delete %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/infos/new.html.erb
<div class="admin-page">
<h3>Nieuw bericht op hoofdpagina "De Trouwdag"</h3>
<div class="admin-menu">
<%= render 'admin/menu' %>
</div>

<%= render 'form' %>

<%= link_to 'Back', infos_path %>
</div>

app/views/infos/nieuws.html.erb
<div class="row">
	<div class="large-6 columns">
		<%= image_tag("side.png" , :class => "simg") %>
	</div>
	<div class="large-6 columns dright">
		<h2 class="vintage">07-08-14</h1>
		<div class="tab">
			<div class="tabtx scroller pacifico">
			<h4> Laatste Nieuws</h4>
			<div class="century">
  			<% @infos.each do |info| %>
    		
      		<h5 class="century"><%= info.titel %></h5>
      		<p><%= info.cont %></p>
    		
  			<% end %>
			</div>
			</div>
		</div>
	</div>
</div>

app/views/infos/show.html.erb
<div class="admin-page">
  <h3>Bericht weergeven</h3>
  <div class="admin-menu">
    <%= render 'admin/menu' %>
  </div>
  <div class="admin-form">
<p>
  <strong>Titel bericht:</strong>
  <%= @info.titel %>
</p>
<p>
  <strong>Inhoud:</strong>
  <%= @info.cont %>
</p>

    <div class="admin-back">
    <%= link_to 'Back',  infos_path %>
    </div>
    </div>
</div>

app/views/layouts/_menu.html.erb
<div id="menu">
	<div class="handprint">
	<%= link_to "De Trouwdag", root_path %>
    <%= link_to "RSVP", newrsvp_path%>
    <% if current_user == admin%>
  	<%= link_to "Admin", admin_path %>
  	<%= link_to "Log out", log_out_path %>
  <% end%>
    
    <!-- 
    <%= link_to "Nieuws", nieuws_path %>
   
    <%= link_to "Fotoboek", fotoboek_path %>
   	
    
   -->
  <!-- <div id="user_nav">
  <% if current_user %>
    ingelogd als <%= current_user.naam %>.
    
    
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
  </div> -->
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "RSVP" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
    
  </head>

  <body>


	
	
	<div class="row display" id="plate">
	
	
	<div class="large-10 small-centered columns">
	<%= render 'layouts/menu' %>
    <%= yield %>
	</div>
	
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/fake_app.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rsvp2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
</head>
<body>
<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.naam %>.
    <%= link_to "Log out", log_out_path %>
    
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
  
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => {:multipart => true} do |f|%>
  <% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
   <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.label :remote_image_url, "or image URL" %><br />
    <%= f.text_field :remote_image_url %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>
 
<%= render 'form' %> 
<%= link_to 'Back',  users_path %>

app/views/posts/fotoboek.html.erb
<div class="row">
	<div class="large-6 columns">
		<%= image_tag("side.png" , :class => "simg") %>
	</div>
	<div class="large-6 columns dright">
		<h2 class="vintage">14-08-14</h1>
		<div class="tab">
			<div class="tabtx scroller pacifico">
			<h1>Foto's</h1>
			<%= link_to 'Nieuwe Foto', new_post_path %> 
			<table>
 			<tr>
    		<th>Titel</th>
    		<th>Foto</th>
  			</tr>
 	
  			<% @posts.each do |post| %>
    		<tr>
      		<td><%= post.title %></td>
      		<td><%= image_tag post.image_url(:thumb) if post.image? %></td>
       		<td><%= link_to 'Show', post %></td>
    
    		</tr>
  			<% end %>
			</table>
			</div>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<div class="admin-page">
    <h3>Lijst met Foto's en opties</h3>
    <div class="admin-menu">
      <%= render 'admin/menu' %>
    </div>
    <div class="admin-sub-menu">
    <%= link_to 'Nieuwe Foto', new_post_path %>
      </div>
    <table>
      <tr>
        <th>Title</th>
        <th>Text</th>
      </tr>

      <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= image_tag post.image_url(:thumb) if post.image? %></td>
           <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= button_to 'Destroy', post_path(post), method: :delete %></td>
        </tr>
      <% end %>
    </table>
</div>

app/views/posts/new.html.erb
<div class="row">
	<div class="large-6 columns">
		<%= image_tag("side.png" , :class => "simg") %>
	</div>
	<div class="large-6 columns dright">
		<h2 class="vintage">14-08-14</h1>
		<div class="tab">
			<div class="tabtx scroller pacifico">
<h1>Nieuwe Foto</h1>

<br />
<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="row">
	<div class="large-6 columns">
		<%= image_tag("side.png" , :class => "simg") %>
	</div>
	<div class="large-6 columns dright">
		<h2 class="vintage">14-08-14</h1>
		<div class="tab">
			<div class="tabtx scroller pacifico">
			<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
<p> <%= image_tag @post.image_url if @post.image? %></p>
 <p>
  <strong>Gebruiker:</strong>
  <%= @post.user.naam %>
</p> 



<h2>Comments</h2>


<% @post.comments.each do |comment| %>
  
    <%	if comment.user_id.nil? %>
   		<p> there is no object <p>
   <% else %>
   <p>
    <strong>User:</strong>
    	<%= comment.user.naam%>
   </p>
   	
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
  <p>
    <strong>Text:</strong>
    <%= comment.body %>
  </p>
   <% end %>
  
 
<% end %>

 <h2>Add a comment:</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :titel %><br />
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %> 
			</div>
		</div>
	</div>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
   <p>
    <%= f.label :naam %>
    <%= f.text_field :naam %>
  </p>
  <p>
    <%= f.label :urlname %>
    <%= f.text_field :urlname %>
  </p>
 <p >
    <%= f.label :answer%>
    <%= f.select :answer, [['Niet gereageerd', 0],['Gaat', 1], ['Gaat Niet', 2], ['Misschien', 3]] %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.text_field :password%>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/edit.html.erb
<div class="admin-page">
  <h3>Gegevens gast aanpassen</h3>
  <div class="admin-menu">
    <%= render 'admin/menu' %>
  </div>
  <div class="admin-form">
<%= render 'form' %> 
<%= link_to 'Back', users_path %>
      </div>
    </div>

app/views/users/index.html.erb
<div class="admin-page">
    <h3>Uitgenodigde gasten</h3>
    <div class="admin-menu">
        <%= render 'admin/menu' %>
    </div>
    <div class="admin-sub-menu">
        <%= link_to 'Nieuwe Gast Toevoegen', new_user_path %>
    </div>
  <div class="admin-table">
    <table>
      <tr>
        <th>Naam Gast</th>
        <th>RSVP</th>
        <th>Wachtwoord</th>
      </tr>

      <% @users.each do |user| %>
        <tr>
          <td><%= user.naam %></td>
          <% if user.answer == 0 %>
          <td> Nog geen reactie</td>
         <% end%>
          <% if user.answer == 1 %>
          <td class="groen"> GAAT naar bruiloft</td>
         <% end%>
          <% if user.answer == 2 %>
          <td class="oranje"> gaat NIET naar de bruiloft</td>
         <% end%>
          <% if user.answer == 3 %>
              <td> gaat MISSCHIEN</td>
          <% end%>
          <td><%= user.password%></td>
           <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= button_to 'Destroy', user_path(user), method: :delete %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<div class="admin-page">
    <h3>Nieuwe Gast</h3>

  <div class="admin-menu">
    <%= render 'admin/menu' %>
  </div>

    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited
          this post from being saved:</h2>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
      <% end %>
       <p>
        <%= f.label :naam %>
        <%= f.text_field :naam %>
      </p>
     <p >
        <%= f.label :answer%>
        <%= f.select :answer, [['Niet gereageerd', 0],['Gaat', 1], ['Gaat Niet', 2], ['Misschien', 3]] %>
      </p>
      <p>
        <%= @a = ["Strand", "Barbeque", "Spareribs", "Tiki", "Hawaii", "Vuur", "Bruid", "Jurk", "Boeket", "Taart", "Dessert", "Wijn", "Ring", "Rozen", "Bikini", "Zand", "Water", "Lucht", "Vakantie", "Feest", "Party", "Foto", "Dans", "Vreugde", "Trouw", "Surfen", "Blauw", "Zee" ]

        @random_password = (@a[rand(@a.length)] + @a[rand(@a.length)]) %>
        <%= f.label :password %>
        <%= f.hidden_field :password, :value => @random_password %>

      </p>
      <p>
        <%= f.label :urlname %>
        <%= f.text_field :urlname %>
      </p>
      <p>
        <%= f.submit %>
      </p>
    <% end %>

    <%= link_to 'Back', users_path %>
</div>

app/views/users/newrsvp.html.erb
<div class="admin-page">
  <div class="guest-form">
    <h3>Meld je aan voor de bruiloft</h3>

 

    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited
          this post from being saved:</h2>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
      <% end %>

       <p>
        <%= f.label :naam %>
        <%= f.text_field :naam, :onkeyup => "fillinurl()", :id => "name" %>
      </p>
     <p >
        <label>Antwoord</label>
        <%= f.select :answer, [['Niet gereageerd', 0],['Gaat', 1], ['Gaat Niet', 2], ['Misschien', 3]] %>
      </p>
      <p>
        <%= f.label :Reden %>
        <%= f.text_field :reason %>
      </p>
      <div class="hidden">
      <p>
      	 <label>Wachtwoord</label>
        <%= @a = ["Strand", "Barbeque", "Spareribs", "Tiki", "Hawaii", "Vuur", "Bruid", "Jurk", "Boeket", "Taart", "Dessert", "Wijn", "Ring", "Rozen", "Bikini", "Zand", "Water", "Lucht", "Vakantie", "Feest", "Party", "Foto", "Dans", "Vreugde", "Trouw", "Surfen", "Blauw", "Zee" ]

        @random_password = (@a[rand(@a.length)] + @a[rand(@a.length)]) %>
       
        <%= f.hidden_field :password, :value => @random_password %>

      </p>
     
      <p>
        <%= f.label :urlname, 'Persoonlijke Pagina Link' %>
        <%= f.text_field :urlname, :id => "urlname", :readonly => true  %>
      </p>
      <p>
      </div>
        <%= f.submit "Sla op"%>
      </p>
    <% end %>
    <div class="admin-back">
      <% if current_user == admin %>
          <%= link_to 'Terug', users_path %>
      <% else %>
          <%= link_to 'Terug', root_path %>
      <%end %>

    </div>
  </div>


</div>

 <script type="text/javascript">
   function fillinurl()
   {
      document.getElementById('urlname').value = document.getElementById('name').value.replace(/\s/g, '');
      document.getElementById('showurl').value = document.getElementById('name').value.replace(/\s/g, '');
      
   }
 </script>

app/views/users/rsvpshow.html.erb
<p>
  <div class="row">
	<div class="large-6 columns">
		<%= image_tag("side.png" , :class => "simg") %>
	</div>
	<div class="large-6 columns dright">
		<h2 class="vintage">RSVP</h2>

		<div class="tab">
			<div class="tabtx scroller pacifico">
              <h4> Beste <%= @user.naam %></h4>
 <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %> 
 
<%= form_for :user, url: user_path(@user), method: :put do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <h5>
    Geef hieronder jouw RSVP antwoord door
  </h5>
  <p>  <%= f.select :answer, [['Nog niet gereageerd', 0],['Gaat Wel naar Bruiloft', 1], ['Gaat Niet', 2], ['Misschien', 3]] %>
  </p>
 
  <p>
  	 <p>
        <%= f.label :Reden %>
        <%= f.text_field :reason %>
      </p>
    <%= f.submit "Sla op" %>
  </p>
<% end %>
  
 
			</div>
		</div>
	</div>
</div>
  

app/views/users/show.html.erb
<div class="admin-page">
  <div class="admin-menu">
  <% if current_user == admin %>
     <%= render 'admin/menu' %>
  <%end %>
  </div>
  <h3>Beste <%= @user.naam %>, </h3>
  <h4>Hartelijk dank voor jouw inschrijving!</h4>

  <h4>Groetjes,  Scarlett en Koen</h4>
         <br/>

   <div class="admin-form century">
     <h5>
       Mocht je naderhand jouw inschrijving willen aanpassen, dan kan het met onderstaande link. Schrijf het indien nodig op:
     </h5>
    <p>
      <%= "www.scarlettenkoentrouwen.nl/" + @user.urlname %>
    </p>

	</br>
    <p >
      <strong>Jouw RSVP antwoord: </strong>
      <% if @user.answer == 1 %>
      <strong>Ja, ik kom naar de bruiloft</strong>
      <% elsif @user.answer == 0%>
      Nog geen reactie
      <% elsif @user.answer == 3%>
      Misschien
      <% else %>
      <strong>Ik ga niet</strong>
      <%end%>
     </br>
    </p>
     <%	 if @user.answer == 2 || @user.answer == 3 %>
     <p>
      <strong>De reden voor jouw reactie: </strong>
      
      <%= @user.reason %>
    </p>
         <%end%>
   
     <div class="admin-back">
       <% if current_user == admin %>
           <%= link_to 'Terug', users_path %>
       <% else %>
           <%= link_to 'Terug', root_path %>
       <%end %>

     </div>
  </div>
</div>